README.md

Updated "Create a buildspec.yml" segment and added "Current process steps" and "Environment Variables" segment

Updated "README.md"

---

deploy.sh

Implement scheduled tasks without service

---

README.md
build.sh
deploy.sh
main.sh

Register NewRelic deployment to APM

---

README.md
deploy.sh

Use a variable on codebuild $DEPLOYMENT_CIRCUIT_BREAKER_RULE with the content "enable=true,rollback=true" to enable/disable Circuit Breaker.
Default value will be "enable=true,rollback=true" if the variable does not exist.

Option to enable or disable circuit breaker

---

.github/workflows/release.yml

Changes to automate Maestro deploy

Changes to automate Maestro deploy

---

.github/workflows/release.yml

**Changes:**
Add checkout step to GitHub Actions workflow file.

Add checkout step

---

README.md

Chanegs in readme for the automate deploy feature

Readme deploy changes

---

.github/workflows/pr-docker-image.yml
.github/workflows/remove-image.yml

Add a new workflow to remove a image in ECR after the pull request is close.

Add new workflow

---

.github/workflows/pr-docker-image.yml
README.md

Fix environment variable error

Pr image/feature

---

.github/workflows/pr-docker-image.yml
.github/workflows/remove-image.yml

Complete the pull request "pre-image" feature

Complete pr image/feature

---

.github/workflows/remove-image.yml

Change the tag variable in remove-img workflow because other valor is received after a merge

Change tag variable format

---

build.sh
deploy.sh
release.sh

Create a cluster with capacity provider, using FARGATE_SPOT as default, but with FARGATE enabled too.

Create a cluster

---

deploy.sh

Adds functionality to propagate tags from tasks definitions to scheduled tasks.

Propagate tags to scheduled tasks from eventBridge

---

.github/workflows/update-pr-image.yml

This feature will increment the ones that already compose the Maestro, making a new AMI be made after a "update" in PR.

Update PR-Docker image feature

---

README.md
deploy.sh
main.sh

Add optional links to deploy alert feature.

Update deploy webhook feature

---

README.md
main.sh

Fix the file-prefix in the variables names.

Fix variables name

---

README.md
main.sh
render.sh
templates/task-definition.json

This pull request enable set the task definition stoptimeout

Set task definition stoptimeout 

---

README.md
deploy.sh

When registering deployment with NewRelic APM, add more info like, user revision name, changelog, description and timestamp.

More info on registering NewRelic deployment

---

README.md
provision.sh

Add to Maestro the ability to reuse load balancers.

Reuse Load Balancer

---

build.sh
deploy.sh
main.sh
provision.sh
release.sh
render.sh

Add EC2 capacity provider in cluster creation.

Add EC2 capacity provider
